/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Metodos.*;
import Vistas.frameCorridas;

/**
 *
 * @author Migue
 */
public class frameMediaVarianza extends javax.swing.JFrame {

    /**
     * Creates new form framePrincipal
     */
    private final String ruta = System.getProperties().getProperty("user.dir");
    Metodos prueba = new Metodos();
    frameCorridas c = new frameCorridas();
    FileReader fr = null;
    BufferedReader br = null;
    JFileChooser fc = new JFileChooser();
    File archivo = null;

    public frameMediaVarianza() throws FileNotFoundException, IOException {
        initComponents();
        this.setTitle("SIMULACION UNIDAD 2");
        if (archivo == null) {
            jButton1.setEnabled(false);
        } else {
            jButton1.setEnabled(true);

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        limInferior1 = new javax.swing.JTextField();
        sumatoria = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        z = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        z2 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        limSuperior1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Resultado1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        limInferior2 = new javax.swing.JTextField();
        media = new javax.swing.JTextField();
        limSuperior2 = new javax.swing.JTextField();
        Varianza = new javax.swing.JTextField();
        Resultado2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        alfa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        conf = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 153, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(102, 255, 255));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 220, 130));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pruebas Estadísticas en Números Pseudoaleatorios");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Media =");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Limite Inferior =");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        limInferior1.setEditable(false);
        limInferior1.setBackground(new java.awt.Color(0, 153, 153));
        limInferior1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        limInferior1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(limInferior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 160, -1));

        sumatoria.setBackground(new java.awt.Color(0, 153, 153));
        sumatoria.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        sumatoria.setForeground(new java.awt.Color(255, 255, 255));
        sumatoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumatoriaActionPerformed(evt);
            }
        });
        jPanel1.add(sumatoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 160, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sumatoria =");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Alfa =");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Z =");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 490, -1, -1));

        z.setBackground(new java.awt.Color(0, 153, 153));
        z.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        z.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(z, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 160, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Z =");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 430, -1, -1));

        z2.setBackground(new java.awt.Color(0, 153, 153));
        z2.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        z2.setForeground(new java.awt.Color(255, 255, 255));
        z2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                z2ActionPerformed(evt);
            }
        });
        jPanel1.add(z2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 430, 130, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Limite Superior =");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 550, -1, -1));

        limSuperior1.setEditable(false);
        limSuperior1.setBackground(new java.awt.Color(0, 153, 153));
        limSuperior1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        limSuperior1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(limSuperior1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 550, 160, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Hipotesis =");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 580, -1, -1));

        Resultado1.setEditable(false);
        Resultado1.setBackground(new java.awt.Color(0, 153, 153));
        Resultado1.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        Resultado1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Resultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 160, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Limite Inferior =");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 460, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Varianza =");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Limite Superior =");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 490, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Prueba de Corridas");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 640, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Calcular Media y Varianza");
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 570, 235, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Hipotesis");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 520, -1, -1));

        limInferior2.setEditable(false);
        limInferior2.setBackground(new java.awt.Color(0, 153, 153));
        limInferior2.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        limInferior2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(limInferior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 460, 160, -1));

        media.setEditable(false);
        media.setBackground(new java.awt.Color(0, 153, 153));
        media.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        media.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(media, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 460, 160, -1));

        limSuperior2.setEditable(false);
        limSuperior2.setBackground(new java.awt.Color(0, 153, 153));
        limSuperior2.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        limSuperior2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(limSuperior2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 490, 160, -1));

        Varianza.setEditable(false);
        Varianza.setBackground(new java.awt.Color(0, 153, 153));
        Varianza.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        Varianza.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Varianza, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 160, -1));

        Resultado2.setEditable(false);
        Resultado2.setBackground(new java.awt.Color(0, 153, 153));
        Resultado2.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        Resultado2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(Resultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 160, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Sans Typewriter", 2, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prueba de Media");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 179, -1));

        alfa.setBackground(new java.awt.Color(0, 153, 153));
        alfa.setFont(new java.awt.Font("Calisto MT", 1, 14)); // NOI18N
        alfa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(alfa, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 160, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Lucida Sans", 2, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Prueba de Varianza");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 360, 185, -1));

        jLabel6.setFont(new java.awt.Font("Malgun Gothic", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Porcentaje de confiabilidad % ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        conf.setBackground(new java.awt.Color(0, 102, 102));
        conf.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        conf.setForeground(new java.awt.Color(255, 255, 255));
        conf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(conf, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 30, 30));

        jButton3.setBackground(new java.awt.Color(51, 255, 204));
        jButton3.setText("Seleccionar archivo .txt");
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 188, -1));

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (conf.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el % de confiabilidad");
        } else {
            prueba.media(this, jTable1, conf, sumatoria, alfa, media, z, limInferior1, limSuperior1, Resultado1);
            prueba.varianza(this, jTable1, conf, Varianza, z2, limInferior2, limSuperior2, Resultado2);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        c.setVisible(true);
        c.setLocationRelativeTo(null);
        c.setSize(610, 600);
        this.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void sumatoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumatoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sumatoriaActionPerformed

    private void z2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_z2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_z2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        try {

            archivo = new File(ruta + "//archivo.txt");
            fr = new FileReader(archivo);
            br = new BufferedReader(fr);
            String linea;
            DefaultTableModel model_tabla = new DefaultTableModel();
            model_tabla.addColumn("Datos de .txt");
            while ((linea = br.readLine()) != null) {
                //model_tabla.addColumn(new String[] {linea});
                model_tabla.addRow(new String[]{linea});
            }

            jTable1.setModel(model_tabla);
            jButton1.setEnabled(true);

        } catch (IOException e) {
        } finally {
            try {
                if (null != fr) {
                    fr.close();
                }
            } catch (IOException e2) {
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frameMediaVarianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frameMediaVarianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frameMediaVarianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frameMediaVarianza.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new frameMediaVarianza().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(frameMediaVarianza.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Resultado1;
    private javax.swing.JTextField Resultado2;
    private javax.swing.JTextField Varianza;
    private javax.swing.JTextField alfa;
    private javax.swing.JTextField conf;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField limInferior1;
    private javax.swing.JTextField limInferior2;
    private javax.swing.JTextField limSuperior1;
    private javax.swing.JTextField limSuperior2;
    private javax.swing.JTextField media;
    private javax.swing.JTextField sumatoria;
    private javax.swing.JTextField z;
    private javax.swing.JTextField z2;
    // End of variables declaration//GEN-END:variables
}
